name: C/C++ CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Configure CMake
      # Agar loyihangizda CMake bo'lsa, bu qismni qoldiring. 
      # Agar oddiy Makefile bo'lsa, pastdagi 'Build' qismini o'zgartiramiz.
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure
