name: C++ CI (Calculator)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential g++

    - name: Build with Makefile
      # Makefile-dagi 'all' qoidasini ishga tushiradi (build papkasini ochadi va kompilyatsiya qiladi)
      run: make all

    - name: Run Test
      # Makefile-dagi 'run' qoidasini ishga tushiramiz. 
      # Bu avtomatik ravishda ./build/calculator.exe ni chaqiradi.
      run: make run
